name = "SatelliteSpots"
uuid = "05d5f3ad-3e1d-4e78-88bc-95e11a320b34"
authors = ["mileslucas <mdlucas@hawaii.edu> and contributors"]
version = "0.1.0"

[deps]
PSFModels = "9ba017d1-7760-46cd-84a3-1e79e9ae9ddc"
Photometry = "af68cb61-81ac-52ed-8703-edc140936be4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
PSFModels = "0.6"
Photometry = "0.8"
julia = "1.6"
